# Generated by Django 4.2.28 on 2026-02-27 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(max_length=500)),
                ('input_channels', models.IntegerField(default=7)),
                ('hidden_dims', models.CharField(default='[16,32,16]', help_text='JSON строка с размерностями скрытых слоев', max_length=100)),
                ('val_loss', models.FloatField(blank=True, null=True)),
                ('test_loss', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('sequence_length', models.IntegerField(default=30, help_text='Длина входной последовательности (дни)')),
                ('forecast_horizon', models.IntegerField(default=30, help_text='Горизонт прогноза (дни)')),
                ('input_data_path', models.CharField(blank=True, max_length=500, null=True)),
                ('output_data_path', models.CharField(blank=True, max_length=500, null=True)),
                ('plot_path', models.CharField(blank=True, max_length=500, null=True)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('logs', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mean_ice_concentration', models.FloatField()),
                ('min_ice_concentration', models.FloatField()),
                ('max_ice_concentration', models.FloatField()),
                ('ice_area', models.FloatField(help_text='Площадь льда в млн км²')),
                ('ice_edge_latitude', models.FloatField(help_text='Средняя широта границы льда')),
                ('full_data', models.JSONField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='predictor.predictionjob')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('job', 'date')},
            },
        ),
    ]
